Promise.resolve().then(() => Promise.reject('err'))
